name: github pages

on:
  push:
    branches: ["main"]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Zig and build the wasm binary
        run: |
          VERSION=0.15.1
          mkdir /tmp/zig
          pushd /tmp/zig
          curl -LO https://ziglang.org/download/$VERSION/zig-x86_64-linux-$VERSION.tar.xz
          tar -xf zig-x86_64-linux-$VERSION.tar.xz
          popd
          /tmp/zig/zig-x86_64-linux-$VERSION/zig build -Dtarget=wasm32-freestanding -Doptimize=ReleaseSmall
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Deploy only the site files
          path: 'zig-out'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
